# Generated by Django 6.0.7 on 2026-08-05 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_create_customer_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='customers.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='idx_usage_event_timestamp'), models.Index(fields=['customer'], name='idx_usage_event_customer')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'timestamp'), name='unique_usage_event_customer_timestamp'), models.CheckConstraint(condition=models.Q(('kwh__gte', 0)), name='usage_event_kwh_non_negative')],
            },
        ),
    ]
