# Generated by Django 6.0.7 on 2026-07-25 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_create_line_item'),
        ('customers', '0001_create_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='customers.customer'),
            preserve_default=False,
        ),
    ]
