[pytest] 
; init format section name

DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py

; Used by pytest
; Which filenames are test files (space-separated patterns):
; tests.py — e.g. billing/tests.py
; test_*.py — e.g. test_api.py
; *_tests.py — e.g. hourly_tests.py


; Fixed	Yours
; DJANGO_SETTINGS_MODULE
; Fixed pytest-django setting
; config.settings
; Yours — your settings module