[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py


; Fixed	Yours
; DJANGO_SETTINGS_MODULE
; Fixed pytest-django setting
; config.settings
; Yours — your settings module