# Generated by Django 6.0.7 on 2026-07-25 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_create_customer_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ContractMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.meter')),
            ],
            options={
                'unique_together': {('contract', 'meter')},
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='meters',
            field=models.ManyToManyField(related_name='contracts', through='contracts.ContractMeter', to='contracts.meter'),
        ),
    ]
